spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  config:
    import:
      - classpath:/application.yml
      - classpath:/application-db.yml
      - classpath:/application-jwt.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher