spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/altinus_pretest?serverTimezone=UTC&characterEncoding=UTF-8
    username: altinus
    password: altinus1234
  redis:
    host: localhost
    port: 6379